### ISSUE TITLE
Auto Update has been added to the official launcher

### ISSUE THREAD

**Issue by Smart123s** [Doregon/minecraft-repo#1]
So I've found your repo, because I was looking for a way to automatically update my MC launcher.

However, I think that this has become unnecessary, since (according to the [changelog](https://minecraft.gamepedia.com/Launcher_2.2.21xx)) in version 2.2.2159 an auto updater for Linux had been introuduced:

> Introduced automatic update functionality on Linux (similar to macOS and Windows).
March 1, 2021

I think that that's the reason why Mojang changed the way they are versioning their .deb files. Also, the size of the .deb files have decreased from 60+MB to 873KiB. I think that these .deb files are now just downloaders for the actual launcher.

Also, I've downloaded two random versions from the [Wayback Machine's copies of Minecraft.deb files](https://web.archive.org/web/*/https://launcher.mojang.com/download/Minecraft.deb). Then I've check their versions returned by the [version checking command in your script](https://github.com/Doregon/minecraft-repo/blob/main/updatemc.sh#L15). And they've matched the versions that they were supposed to be according to the [MC Wiki's Launcher version history](https://minecraft.gamepedia.com/Launcher_version_history).
[2020-11-01](https://web.archive.org/web/20201101191523if_/https://launcher.mojang.com/download/Minecraft.deb): 2.1.17785
[2021-02-02](https://web.archive.org/web/20210202005437if_/https://launcher.mojang.com/download/Minecraft.deb): 2.2.1441

**Comment by Doregon** [comment]
Alright, thanks for letting me know. I recently switched to Manjaro and noticed that installing the AUR package for minecraft-launcher caused an automatic updater to launch without requiring to manually do anything else, and I thought that was an Arch-only thing.

**Comment by Doregon** [comment]
Just to make sure, I won't archive this repository until a new Launcher update is available. I hope to see what happens, and whether or not it updates without this repo. Since I don't have a Debian-based distro of Linux anymore, do you think you could help with finding out (once the time comes?) @Smart123s

**Comment by Smart123s** [comment]
Of course, just let me know when that happens.

**Comment by Doregon** [comment]
Thanks! I'll be reopening this until then.

**Comment by Doregon** [comment]
@Smart123s Alright, the current version of the launcher is now 915. This APT repo just got it (there was an error with my shell scripts and GitHub Actions wasn't running it correctly), but it's time to see if it automatically updates without this repository. I suggest that you install an older version first using `sudo apt install minecraft-launcher=887` and then remove the repository as you test.

**Comment by Smart123s** [comment]
So, I had `minecraft-launcher v887` installed on my system (without your repo).
I've launched the game and the updater started. I'we waited till the game opened up. Then I've closed it and reopened the launcher. This time, no updater has appeared. However `apt list --installed | grep minecraft` still returned `v887`. Also, I did **NOT** get an "Update your Launcher" prompt in the top right of the launcher.

**Comment by Doregon** [comment]
What does it say in the Launcher's Settings > About section? (btw I noticed that the new versioning is under **Bootstrap**).

**Comment by Smart123s** [comment]
I've created a VM and installed https://github.com/Doregon/minecraft-repo/blob/main/debs/Minecraft-887.deb in it.
This is it's about page:
<img width="866" alt="Screenshot 2021-03-12 090524" src="https://user-images.githubusercontent.com/28480228/110911056-79bcd300-8312-11eb-8c29-10cd9103b8bd.png">

**Comment by Doregon** [comment]
Alrighty then, I'm archiving this repository (so that other people can use it as a base for their own repositories, if they need it), and thanks for letting me know about this!
